Categories:
  - Internet
  - System
License: GPL-3.0-only
AuthorName: swtkiptr
SourceCode: https://github.com/swtkiptr/ntfy-hook
IssueTracker: https://github.com/swtkiptr/ntfy-hook/issues
Changelog: https://github.com/swtkiptr/ntfy-hook/releases
WebSite: https://github.com/swtkiptr/ntfy-hook

AutoName: ntfy Hook
Summary: Forward Android notifications to ntfy servers
Description: |
  ntfy Hook is a simple Android application that forwards notifications to ntfy servers.
  
  Features:
  - Forward notifications from any app to ntfy
  - Customize which apps to monitor
  - Filter notifications by content
  - Run reliably in the background
  - Lightweight and battery-efficient

RepoType: git
Repo: https://github.com/swtkiptr/ntfy-hook
Binaries: https://github.com/swtkiptr/ntfy-hook/releases/download/v%v/app-release.apk

Builds:
  - versionName: 1.0.0
    versionCode: 3
    commit: v1.0.0
    subdir: app
    gradle:
      - yes
  - versionName: 1.0.1
    versionCode: 4
    commit: v1.0.1
    subdir: app
    gradle:
      - yes
  - versionName: 1.0.2
    versionCode: 5
    commit: v1.0.2
    subdir: app
    gradle:
      - yes
  - versionName: 1.0.3
    versionCode: 6
    commit: v1.0.3
    subdir: app
    gradle:
      - yes
  - versionName: 1.0.4
    versionCode: 7
    commit: v1.0.4
    subdir: app
    gradle:
      - yes
  - versionName: 1.0.5
    versionCode: 8
    commit: v1.0.5
    subdir: app
    gradle:
      - yes
  - versionName: 1.0.6
    versionCode: 9
    commit: v1.0.6
    subdir: app
    gradle:
      - yes
    output: app/build/outputs/apk/release/app-release-unsigned.apk
    prebuild: sed -i -e '/signingConfig/d' build.gradle.kts

MaintainerNotes: |
  This app doesn't use any native code, so multiple APKs for different architectures are not needed.
  No external repositories are used as git submodules.
  Reproducible builds are enabled in build.gradle.kts.

AllowedAPKSigningKeys: 4cd08d51d7177b436eb3e3c9157410e31f0ef6ffbda0915f84fc0b99602fc501

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.0.6
CurrentVersionCode: 9