Categories:
  - Internet
  - System
License: GPL-3.0-only
AuthorName: swtkiptr
SourceCode: https://github.com/swtkiptr/ntfy-hook
IssueTracker: https://github.com/swtkiptr/ntfy-hook/issues
Changelog: https://github.com/swtkiptr/ntfy-hook/releases

AutoName: ntfy Hook

RepoType: git
Repo: https://github.com/swtkiptr/ntfy-hook
Binaries: https://github.com/swtkiptr/ntfy-hook/releases/download/v%v/app-release.apk

Builds:
  - versionName: 1.0.6
    versionCode: 9
    commit: v1.0.6
    subdir: app
    gradle:
      - yes

AllowedAPKSigningKeys: 4cd08d51d7177b436eb3e3c9157410e31f0ef6ffbda0915f84fc0b99602fc501

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.0.6
CurrentVersionCode: 9