name: Android Build and Publish on Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ntfy-hook-${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up JDK
        uses: actions/setup-java@v4 # Updated to latest version
        with:
          java-version: '17'
          distribution: 'temurin' # Recommended for consistency

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # Fix for Permission denied error

      - name: Build AAB
        run: |
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon --warning-mode all

      - name: Sign AAB
        id: sign_app_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Copy AAB
        run: |
          cp ${{ steps.sign_app_aab.outputs.signedReleaseFile }} ${{ env.APP_NAME }}.aab

      - name: Build APK
        run: |
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon --warning-mode all

      - name: Sign APK
        id: sign_app_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Copy APK
        run: |
          cp ${{ steps.sign_app_apk.outputs.signedReleaseFile }} ${{ env.APP_NAME }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2 # Updated to latest version
        with:
          files: |
            ${{ env.APP_NAME }}.apk
            ${{ env.APP_NAME }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
